// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlRRBhswC0GypP51eVAFQqvB6V4mzIFu0',
    appId: '1:938393050592:web:45c7659615808cdb681f85',
    messagingSenderId: '938393050592',
    projectId: 'senarchive-cb8f6',
    authDomain: 'senarchive-cb8f6.firebaseapp.com',
    storageBucket: 'senarchive-cb8f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo1SDkA7O3wvbRzlLN0ev58mM6KzpR8j8',
    appId: '1:938393050592:android:e4b9590ad28f824b681f85',
    messagingSenderId: '938393050592',
    projectId: 'senarchive-cb8f6',
    storageBucket: 'senarchive-cb8f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPoLgqu8fD17dKqywLNijvMy3eMEawto',
    appId: '1:938393050592:ios:0a8e086e83d80e49681f85',
    messagingSenderId: '938393050592',
    projectId: 'senarchive-cb8f6',
    storageBucket: 'senarchive-cb8f6.firebasestorage.app',
    iosBundleId: 'com.example.senArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALPoLgqu8fD17dKqywLNijvMy3eMEawto',
    appId: '1:938393050592:ios:0a8e086e83d80e49681f85',
    messagingSenderId: '938393050592',
    projectId: 'senarchive-cb8f6',
    storageBucket: 'senarchive-cb8f6.firebasestorage.app',
    iosBundleId: 'com.example.senArchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlRRBhswC0GypP51eVAFQqvB6V4mzIFu0',
    appId: '1:938393050592:web:acbaea019bc9850e681f85',
    messagingSenderId: '938393050592',
    projectId: 'senarchive-cb8f6',
    authDomain: 'senarchive-cb8f6.firebaseapp.com',
    storageBucket: 'senarchive-cb8f6.firebasestorage.app',
  );
}
